spring.application.name=banking-platform
#
spring.profiles.default=local
#
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.jakarta.persistence.lock.timeout=5000
#
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
#
management.endpoints.web.exposure.include=health,info
#

